#!/usr/bin/env bash

api-doc () {
    sbt doc
    now switch xieyuheng
    now -n bebop target/scala-2.12/api/
}

deps () {
    git submodule update --remote
}

main () {
    for TASK in $@
    do
        $TASK
    done
}

main $@
