#!/usr/bin/env bash

api-doc () {
    sbt doc
    now switch xieyuheng
    now -n bebop target/scala-2.12/api/
}

deps () {
    git submodule init
    git submodule update
    git submodule update --remote
    for SUBMODULE in $(find deps/ -maxdepth 1 -mindepth 1)
    do
        pushd SUBMODULE & sbt +publishLocal & popd
    done
}

main () {
    for TASK in $@
    do
        $TASK
    done
}

main $@
